/**
 * Image manifest — every slot generated by scripts/img.py in Phase 6.
 *
 * The <Img> component reads this so a page never hand-writes a srcset. Intrinsic
 * width/height come from here too, so every image reserves its box and CLS
 * stays at zero (audit.py WARNs on a missing dimension).
 *
 * DESIGN.md §7: every GENERATED image is captioned as generated, so nothing
 * that could read as documentary product photography passes unlabelled.
 *
 * The `photo-*` slots are the exception: they are real trip photographs
 * supplied by Semporna Paradise and cleared for publication by the guests in
 * them and by the company owner (clearance of record 2026-09-02, CONTEXT.md
 * §5). They are the only real photographs on the site, they are always shown
 * inside <GuestGallery>, and that component captions them as real guest
 * photos published with permission. Everything else stays generated.
 */

export interface ImageMeta {
  widths: number[];
  /** Intrinsic size of the largest rendition. */
  w: number;
  h: number;
}

export const IMAGES = {
  "home-hero":        { widths: [480, 960, 1440, 1920], w: 1920, h: 1088 },
  "home-intro":       { widths: [480, 960, 1024], w: 1024, h: 768 },
  "home-activity":    { widths: [480, 960, 1280], w: 1280, h: 720 },
  "home-sunset":      { widths: [480, 960, 1280], w: 1280, h: 720 },
  "pakej-hero":       { widths: [480, 960, 1280], w: 1280, h: 720 },
  "resort-generic-1": { widths: [480, 960, 1024], w: 1024, h: 768 },
  "resort-generic-2": { widths: [480, 960, 1024], w: 1024, h: 768 },
  "resort-texture":   { widths: [480, 960, 1024], w: 1024, h: 1024 },
  "harian-hero":      { widths: [480, 960, 1280], w: 1280, h: 720 },
  "harian-island":    { widths: [480, 960, 1024], w: 1024, h: 768 },
  "harian-people":    { widths: [480, 960, 1280], w: 1280, h: 720 },
  "selam-hero":       { widths: [480, 960, 1280], w: 1280, h: 720 },
  "selam-wall":       { widths: [480, 960, 1280], w: 1280, h: 720 },
  "creature-turtle":  { widths: [480, 960, 1024], w: 1024, h: 768 },
  "creature-barracuda": { widths: [480, 960, 1280], w: 1280, h: 720 },
  "creature-reef":    { widths: [480, 960, 1024], w: 1024, h: 1024 },
  "sipadan-deep":     { widths: [480, 960, 1280], w: 1280, h: 720 },
  "rancang-hero":     { widths: [480, 901], w: 901, h: 738 },
  "trust-hero":       { widths: [480, 960, 1280], w: 1280, h: 720 },
  "tentang-hero":     { widths: [480, 960, 1280], w: 1280, h: 720 },
  "hubungi-hero":     { widths: [480, 960, 1024], w: 1024, h: 768 },
  "texture-water":    { widths: [480, 960, 1024], w: 1024, h: 1024 },
  "texture-foam":     { widths: [480, 960, 1024], w: 1024, h: 1024 },
  "og-share":         { widths: [480, 960, 1440, 1920], w: 1920, h: 1088 },

  /* ---- Real guest photographs (cleared 2026-09-02) ------------------- */
  "photo-boat-group":   { widths: [480, 960, 1280], w: 1280, h: 960 },
  "photo-bohey-dulang": { widths: [480, 960, 1280], w: 1280, h: 960 },
  "photo-sandbar-sea":  { widths: [480, 960, 1280], w: 1280, h: 960 },
  "photo-boat-selfie":  { widths: [480, 810], w: 810, h: 1080 },
  "photo-heart-sandbar":{ widths: [480, 810], w: 810, h: 1080 },
  "photo-group-sign":   { widths: [480, 810], w: 810, h: 1080 },
  "photo-boat-thumbs":  { widths: [480, 608], w: 608, h: 1080 },

  /* ---- Free-licence Wikimedia Commons stills (harvested 2026-09-04) ----
     Every one of these is CC0, CC BY or CC BY-SA and is attributed in the
     footer through src/data/photo-credits.ts. CC BY and CC BY-SA REQUIRE that.
     Harvest and licence vetting: scripts/harvest-commons.py. ------------- */
  "cm-semporna-dusk": { widths: [480, 960, 1280, 1920], w: 1920, h: 784 },
  "cm-stilt-lagoon": { widths: [480, 960, 1280, 1920], w: 1920, h: 1080 },
  "cm-reef-mosaic": { widths: [480, 960, 1280, 1920], w: 1920, h: 1920 },
  "cm-stilt-village": { widths: [480, 960, 1280, 1920], w: 1920, h: 1080 },
  "cm-semporna-town": { widths: [480, 960, 1280, 1920], w: 1920, h: 1280 },
  "cm-white-beach": { widths: [480, 960, 1280, 1920], w: 1920, h: 1272 },
  "cm-sipadan-wall": { widths: [480, 960, 1280, 1920], w: 1920, h: 1280 },
  "cm-turtle": { widths: [480, 960, 1280, 1920], w: 1920, h: 1152 },
  "cm-jackfish": { widths: [480, 960, 1280, 1920], w: 1920, h: 1157 },
  "cm-reef-shark": { widths: [480, 960, 1280, 1920], w: 1920, h: 1280 },
  "cm-reef-fish": { widths: [480, 960, 1280, 1920], w: 1920, h: 1440 },
  "cm-wrasse": { widths: [480, 960, 1280, 1920], w: 1920, h: 1535 },
  "cm-bubble-coral": { widths: [480, 960, 1280, 1920], w: 1920, h: 1152 },
} as const satisfies Record<string, ImageMeta>;

export type ImageSlot = keyof typeof IMAGES;

export function srcset(slot: ImageSlot, ext: "webp" | "avif"): string {
  return IMAGES[slot].widths.map((w) => `/img/${slot}-${w}.${ext} ${w}w`).join(", ");
}

/** A mid-size default src for the <img> fallback. */
export function fallbackSrc(slot: ImageSlot): string {
  const ws = IMAGES[slot].widths;
  const mid = ws[Math.min(1, ws.length - 1)];
  return `/img/${slot}-${mid}.webp`;
}
