/**
 * Image manifest — every slot generated by scripts/img.py in Phase 6.
 *
 * The <Img> component reads this so a page never hand-writes a srcset. Intrinsic
 * width/height come from here too, so every image reserves its box and CLS
 * stays at zero (audit.py WARNs on a missing dimension).
 *
 * DESIGN.md §7: every image is generated. None is a photograph of a real,
 * named property or a real person presented as a customer. Captions on any
 * image that could read as documentary product photography say what it is.
 */

export interface ImageMeta {
  widths: number[];
  /** Intrinsic size of the largest rendition. */
  w: number;
  h: number;
}

export const IMAGES = {
  "home-hero":        { widths: [480, 960, 1440, 1920], w: 1920, h: 1088 },
  "home-intro":       { widths: [480, 960, 1024], w: 1024, h: 768 },
  "home-activity":    { widths: [480, 960, 1280], w: 1280, h: 720 },
  "home-sunset":      { widths: [480, 960, 1280], w: 1280, h: 720 },
  "pakej-hero":       { widths: [480, 960, 1280], w: 1280, h: 720 },
  "resort-generic-1": { widths: [480, 960, 1024], w: 1024, h: 768 },
  "resort-generic-2": { widths: [480, 960, 1024], w: 1024, h: 768 },
  "resort-texture":   { widths: [480, 960, 1024], w: 1024, h: 1024 },
  "harian-hero":      { widths: [480, 960, 1280], w: 1280, h: 720 },
  "harian-island":    { widths: [480, 960, 1024], w: 1024, h: 768 },
  "harian-people":    { widths: [480, 960, 1280], w: 1280, h: 720 },
  "selam-hero":       { widths: [480, 960, 1280], w: 1280, h: 720 },
  "selam-wall":       { widths: [480, 960, 1280], w: 1280, h: 720 },
  "creature-turtle":  { widths: [480, 960, 1024], w: 1024, h: 768 },
  "creature-barracuda": { widths: [480, 960, 1280], w: 1280, h: 720 },
  "creature-reef":    { widths: [480, 960, 1024], w: 1024, h: 1024 },
  "sipadan-deep":     { widths: [480, 960, 1280], w: 1280, h: 720 },
  "rancang-hero":     { widths: [480, 901], w: 901, h: 738 },
  "trust-hero":       { widths: [480, 960, 1280], w: 1280, h: 720 },
  "tentang-hero":     { widths: [480, 960, 1280], w: 1280, h: 720 },
  "hubungi-hero":     { widths: [480, 960, 1024], w: 1024, h: 768 },
  "texture-water":    { widths: [480, 960, 1024], w: 1024, h: 1024 },
  "texture-foam":     { widths: [480, 960, 1024], w: 1024, h: 1024 },
  "og-share":         { widths: [480, 960, 1440, 1920], w: 1920, h: 1088 },
} as const satisfies Record<string, ImageMeta>;

export type ImageSlot = keyof typeof IMAGES;

export function srcset(slot: ImageSlot, ext: "webp" | "avif"): string {
  return IMAGES[slot].widths.map((w) => `/img/${slot}-${w}.${ext} ${w}w`).join(", ");
}

/** A mid-size default src for the <img> fallback. */
export function fallbackSrc(slot: ImageSlot): string {
  const ws = IMAGES[slot].widths;
  const mid = ws[Math.min(1, ws.length - 1)];
  return `/img/${slot}-${mid}.webp`;
}
